<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-6H0FSJA9" failures="1" tests="2" name="Test1" time="16.198" errors="0" timestamp="2023-09-16T10:50:39 IST">
  <testcase classname="Testng.Saucedemo3" name="invalidcredinals" time="3.388">
    <failure type="java.lang.AssertionError" message="did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]
at Testng.Saucedemo3.invalidcredinals(Saucedemo3.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- invalidcredinals -->
  <testcase classname="Testng.Saucedemo3" name="validcredinals" time="3.437"/>
</testsuite> <!-- Test1 -->
