<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-16T10:50:22 IST" name="Suite" finished-at="2023-09-16T10:50:39 IST" duration-ms="16198">
    <groups>
    </groups>
    <test started-at="2023-09-16T10:50:22 IST" name="Test1" finished-at="2023-09-16T10:50:39 IST" duration-ms="16198">
      <class name="Testng.Saucedemo3">
        <test-method is-config="true" signature="setup()[pri:0, instance:Testng.Saucedemo3@43195e57]" started-at="2023-09-16T10:50:22 IST" name="setup" finished-at="2023-09-16T10:50:22 IST" duration-ms="350" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="navigateUrl()[pri:0, instance:Testng.Saucedemo3@43195e57]" started-at="2023-09-16T10:50:22 IST" name="navigateUrl" finished-at="2023-09-16T10:50:27 IST" duration-ms="4658" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateUrl -->
        <test-method signature="invalidcredinals(java.lang.String,java.lang.String)[pri:0, instance:Testng.Saucedemo3@43195e57]" started-at="2023-09-16T10:50:27 IST" name="invalidcredinals" finished-at="2023-09-16T10:50:30 IST" duration-ms="3388" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[standard_Invaliduse]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_Invalidpw]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at org.testng.Assert.assertNotEquals(Assert.java:1535)
at Testng.Saucedemo3.invalidcredinals(Saucedemo3.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidcredinals -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:Testng.Saucedemo3@43195e57]" started-at="2023-09-16T10:50:30 IST" name="teardown" finished-at="2023-09-16T10:50:31 IST" duration-ms="247" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="navigateUrl()[pri:0, instance:Testng.Saucedemo3@43195e57]" started-at="2023-09-16T10:50:31 IST" name="navigateUrl" finished-at="2023-09-16T10:50:35 IST" duration-ms="4252" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateUrl -->
        <test-method signature="validcredinals(java.lang.String,java.lang.String)[pri:0, instance:Testng.Saucedemo3@43195e57]" started-at="2023-09-16T10:50:35 IST" name="validcredinals" finished-at="2023-09-16T10:50:38 IST" duration-ms="3437" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[standard_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validcredinals -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:Testng.Saucedemo3@43195e57]" started-at="2023-09-16T10:50:38 IST" name="teardown" finished-at="2023-09-16T10:50:39 IST" duration-ms="181" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- Testng.Saucedemo3 -->
    </test> <!-- Test1 -->
  </suite> <!-- Suite -->
</testng-results>
